name: i_smile_clinic
description: Dental Clinic Management System.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_image_compress: ^2.0.3
  date_picker_timeline: ^1.2.3
  flutter_staggered_animations: ^1.0.0
  awesome_dialog: ^3.0.2
  shimmer: ^3.0.0
  intl: ^0.18.0
  http: ^0.13.5
  provider: ^6.0.5
  image_picker: ^0.8.7+2
  flutter_lints: ^2.0.0
  flutter_bloc: ^8.1.3
  shared_preferences: ^2.2.0
  animated_splash_screen: ^1.3.0
  full_screen_image: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/profileImage.png
    - assets/lang/ar.json
    - assets/lang/en.json
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700
    - family: Anton
      fonts:
        - asset: assets/fonts/Anton-Regular.ttf
